### ISSUE TITLE
Payments page drop down triangles (All platforms) 

### ISSUE THREAD

**Issue by grahamee87** [Electra-project/electra-desktop#103]
Payments page- drop down triangles don’t actually drop down menu, however the rest of the field does and drop down triangle on receive field is partially covering address (may not be all that important)

![image](https://user-images.githubusercontent.com/35108480/38970854-0fde60c0-4355-11e8-83a4-05e9f4a3c5b8.png)

**Comment by ivangabriele** [comment]
I didn't find time to fix this bug but we need to.

**Comment by Hyjaz** [comment]
@ivangabriele  @grahamee87 for now I changed it to the default icon as follow:

<img width="859" alt="screen shot 2018-06-02 at 2 12 14 pm" src="https://user-images.githubusercontent.com/16614359/40879509-143eb2c2-666f-11e8-84a8-f2bda0f38919.png">
Let me know what you guys think.

**Comment by ivangabriele** [comment]
Fixed on v1.1.0:

- Linux (.deb): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop_1.1.0_amd64.deb
- Linux (.rpm): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.x86_64.rpm
- MacOS: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.dmg
- Windows: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-setup-1.1.0.exe
