### ISSUE TITLE
Wallet should indicate coin age/maturity status

### ISSUE THREAD

**Issue by grahamee87** [Electra-project/electra-desktop#105]
Unless coin age/maturity is no longer a requirement for staking.

**Comment by ivangabriele** [comment]
It is. However this kind of feature is far from a priority imo. I would like to move it as a "won
t do". @ruannelloyd ?

**Comment by ivangabriele** [comment]
I will close this one as the "Estimated Accumulated Interests" that has been temporarily removed but will be re-enabled after the fork does that in a more comprehensive way.
