### ISSUE TITLE
Mnemonic Recovery and missing funds

### ISSUE THREAD

**Issue by ElectraBull** [Electra-project/electra-desktop#107]
1. Entered mnemonic phrase to recover funds and it has taken well over 3 hours to load now. 
EDIT: 4 hours

![image](https://user-images.githubusercontent.com/38555896/39044218-e25bd63a-44d2-11e8-9068-a6479ecc9a20.png)

2. QT wallet is no longer reading backup .dat file. Shows "Zero" balance (wallet.dat was replaced with backup)

**Comment by ivangabriele** [comment]
Also it can take up to 2 or 3 minutes to restore you wallet but no more than that. If it takes so long this is because the mnemonic is wrong.

**Comment by ivangabriele** [comment]
Do you still have the issue @ElectraBull ?

**Comment by Jenova7** [comment]
It's what happened with v1.0.8. Must use the 1.0.6 for recovery

**Comment by ivangabriele** [comment]
So ok I've fixed this one, it should not happen with the next release. I will keep this issue opened for the next release checkup.

**Comment by ivangabriele** [comment]
Fixed on v1.1.0:

- Linux (.deb): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop_1.1.0_amd64.deb
- Linux (.rpm): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.x86_64.rpm
- MacOS: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.dmg
- Windows: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-setup-1.1.0.exe
