### ISSUE TITLE
Can't send from legacy to checking W10

### ISSUE THREAD

**Issue by Jenova7** [Electra-project/electra-desktop#110]
We delete Electra desktop folder, restart wallet, same issue
after, uninstall properly the wallet, fresh install, wait for full synch. 
Try to send all (-fees), still the same.

**Comment by ivangabriele** [comment]
You were trying to send  the full amount available in your Legacy Account ?

**Comment by Jenova7** [comment]
yes, it's a duplicate, answered on the #121

**Comment by ivangabriele** [comment]
Close as duplicate of #121.
