### ISSUE TITLE
Add "all" button in payments

### ISSUE THREAD

**Issue by Jenova7** [Electra-project/electra-desktop#113]
Is it possible to add a button which allows to select the totality of the available coins. and maybe automatically subtracting the fees?
![proposition_all](https://user-images.githubusercontent.com/38404798/39183271-bf2d0090-47bf-11e8-9010-a79017d921ee.jpg)

**Comment by Jenova7** [comment]
maybe with a pop up that would say: "you're about to send all the coins of the selected address"
suggested by @eca squirrel

**Comment by ivangabriele** [comment]
This is a good idea, I will implement that for the next minor release.

**Comment by ivangabriele** [comment]
Fixed on v1.1.0:

- Linux (.deb): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop_1.1.0_amd64.deb
- Linux (.rpm): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.x86_64.rpm
- MacOS: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.dmg
- Windows: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-setup-1.1.0.exe
