### ISSUE TITLE
Tiny Bug

### ISSUE THREAD

**Issue by ECA-Ryu** [Electra-project/electra-desktop#114]
https://i.gyazo.com/aa3688202693b9282a1b70d4491aa6c2.png

Tiny bug, it shows that 1.29 ECA is 0.24 BTC.

**Comment by ivangabriele** [comment]
I will try to reproduce that.

**Comment by ivangabriele** [comment]
Fixed on v1.1.0:

- Linux (.deb): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop_1.1.0_amd64.deb
- Linux (.rpm): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.x86_64.rpm
- MacOS: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.dmg
- Windows: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-setup-1.1.0.exe
