### ISSUE TITLE
Desktop Wallet Syncing issues

### ISSUE THREAD

**Issue by ghost** [Electra-project/electra-desktop#117]
Several users have been reporting issues with updating their Desktop wallets.

They have been attempting to sync up using version 1.0.8

One user confirmed they were using windows 10 and another user was on windows 8.1.

They left the wallets open to allow synchronization, and even after the recommended 24 hours. The wallet would not sync for either user.

Had the users test the QT wallet which started the syncing processes immediately. 

It appears with some users the desktop wallet is having issues synchronizing with the nodes.

**Comment by ecacryptonaut** [comment]
Also, we've tested replacing the peers.dat with one that's already been synced with a wallet, and this seems to have speed up synchronization by a lot. Usually within about 45-60 minutes for the wallet to sync.

**Comment by ivangabriele** [comment]
Yes @ecacryptonaut, we definitely need to open more servers. That's in fact one of the reasons I just created [electra-cli](https://github.com/Electra-project/electra-cli) in order to fast deploy new public wallets.

To be checked with @ruannelloyd as how to organize that.

**Comment by ivangabriele** [comment]
I prefer to keep it open in order to keep this issue as a reminder about the need for more bootstrap wallet servers.

**Comment by ivangabriele** [comment]
Fixed on v1.1.0:

- Linux (.deb): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop_1.1.0_amd64.deb
- Linux (.rpm): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.x86_64.rpm
- MacOS: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.dmg
- Windows: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-setup-1.1.0.exe
