### ISSUE TITLE
Does not support 32 bit 

### ISSUE THREAD

**Issue by jayanthmankavil** [Electra-project/electra-desktop#134]

**Comment by ivangabriele** [comment]
Hi @jayanthmankavil !

It has been integrated in the next release which is currently beta-tested.

**Comment by jayanthmankavil** [comment]
Yep win 7, 32 bit architecture

**Comment by ivangabriele** [comment]
Fixed on v1.1.0:

- Linux (.deb): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop_1.1.0_amd64.deb
- Linux (.rpm): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.x86_64.rpm
- MacOS: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.dmg
- Windows: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-setup-1.1.0.exe
