### ISSUE TITLE
Estimated Cummulated Amount

### ISSUE THREAD

**Issue by ruannelloyd** [Electra-project/electra-desktop#136]
Suggestion we remove as we will be changing it to 10% with new fork.

**Comment by ivangabriele** [comment]
We will update it as the fork will require an update anyway.

**Comment by ivangabriele** [comment]
As talked, since it can create a misunderstanding with users regarding the fork behavior, I'm removing it right from the v1.1.0.

**Comment by ivangabriele** [comment]
Done on v1.0.0:

- Linux (.deb): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop_1.1.0_amd64.deb
- Linux (.rpm): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.x86_64.rpm
- MacOS: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.dmg
- Windows: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-setup-1.1.0.exe
