### ISSUE TITLE
Windows - does not have maximise / minimise buttons

### ISSUE THREAD

**Issue by ruannelloyd** [Electra-project/electra-desktop#83]
![screenshot 2018-04-17 14 05 47](https://user-images.githubusercontent.com/35781921/38868758-84900bca-4248-11e8-81e9-9a53b94808e7.png)

**Comment by ivangabriele** [comment]
We will add that in the next version.

**Comment by Hyjaz** [comment]
@ruannelloyd 

This is for windows and linux? I know mac has the minimize and maximize.

**Comment by ivangabriele** [comment]
Yes it is, I will handle it.

**Comment by ivangabriele** [comment]
Done on v1.1.0:

- Linux (.deb): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop_1.1.0_amd64.deb
- Linux (.rpm): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.x86_64.rpm
- MacOS: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.dmg
- Windows: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-setup-1.1.0.exe
