### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ruannelloyd** [Electra-project/electra-desktop#86]
Copy and Paste not working.

**Comment by Hyjaz** [comment]
Copy and paste where? When your trying to copy and paste the mnemonic? Or when you are trying to copy an address?

**Comment by ruannelloyd** [comment]
The address.

**Comment by Hyjaz** [comment]
Works for me...

**Comment by Hyjaz** [comment]
We should parse out the things in brackets

**Comment by sandro-csimas** [comment]
@ruannelloyd, can you please the issue title to be more clear?

**Comment by Hyjaz** [comment]
This works. I will close this issue.
