### ISSUE TITLE
Can't copy the mnemonic when creating a new Wallet.

### ISSUE THREAD

**Issue by sandrosimas** [Electra-project/Electra-Desktop#89]
![image](https://user-images.githubusercontent.com/1282074/38944985-a5833366-430b-11e8-8ac2-bfbc73468c5e.png)
Please provide a way to copy the mnemonic.
This is just a test wallet =P

**Comment by sandro-csimas** [comment]
Yes I know, but this is useless when you want to copy and paste in another document, for example.
I think you should provide this feature and ask the user to confirm.

**Comment by pbp8ntballer** [comment]
@sandro-csimas this is a common feature for other wallets/applications that use mnemonic phrases, making the user to be aware of the importance of recording the phrase by hand, either by writing it down on paper or typing it out in a word document.

**Comment by sandro-csimas** [comment]
@pbp8ntballer, I know it's common feature, but all the wallets I used until now provided a way to copy the entire mnemonic. I'm used to copy the entire mnemonic and save it to a encrypted file with password. I think the process of write by hand into a file and copy (faster) will have the same result here as you can't copy the mnemonic by half. I'm my opinion you can remind the importance of this by displaying a confirmation alert.

Anyway, just my opinion, feel free to close the issue! =P
