### ISSUE TITLE
Add the address of Purse, Checking, Saving and Legacy next to it's respective headers

### ISSUE THREAD

**Issue by Hyjaz** [Electra-project/electra-desktop#90]
can we add the address of each different `account` next to it's header:
![image](https://user-images.githubusercontent.com/16614359/38945456-8afbeddc-4304-11e8-8438-23f2750c4d66.png)

We also need to be able to copy it.

**Comment by ivangabriele** [comment]
I close this one as the planned redesign for the v1.2.0 will include a final decision about that.
