### ISSUE TITLE
Sent shows -0.0000000000 ECA

### ISSUE THREAD

**Issue by Hyjaz** [Electra-project/electra-desktop#95]
![image](https://user-images.githubusercontent.com/16614359/38950520-caf1e342-4313-11e8-8dac-00428aefb3c8.png)

**Comment by ivangabriele** [comment]
Does this bug is still in the v1.0.8 ?

**Comment by Hyjaz** [comment]
This bug is not there anymore in the latest version.

**Comment by ivangabriele** [comment]
@Hyjaz You mean in the 1.0.8 or the dev version ?

**Comment by Hyjaz** [comment]
yes, v1.0.8.

**Comment by ivangabriele** [comment]
Let me ask the support to double check.

**Comment by ivangabriele** [comment]
I close it since the support didn't report seeing that anymore either.
