### ISSUE TITLE
Lost ECA when transfering

### ISSUE THREAD

**Issue by Coolcovey** [Electra-project/electra-desktop#97]
I am missing over 8 million ECA after transfering from legacy to savings and checking accounts. All transactions are now 10/10 confirmations.

**Comment by Hyjaz** [comment]
Can you please show your wallet? the transaction id, address...?

**Comment by Coolcovey** [comment]
![image](https://user-images.githubusercontent.com/38509838/38957806-e60b5e60-4331-11e8-9b43-d2966533a03f.png)

**Comment by Coolcovey** [comment]
when i got the new wallet i had 29.7 mill

**Comment by Coolcovey** [comment]
![image](https://user-images.githubusercontent.com/38509838/38957891-119a1d64-4332-11e8-9a50-65fb7fc2dbb7.png)
![image](https://user-images.githubusercontent.com/38509838/38957907-1cd36f28-4332-11e8-886e-657d1e11c4f5.png)

**Comment by ivangabriele** [comment]
Hi Coolcovey,

It seems that an edge case happened on your transaction. We need to look at that in detail, can you send me an email at ivan.gabriele@gmail.com please, so that we can look at that together ?

**Comment by ivangabriele** [comment]
Closed as solved.
