### ISSUE TITLE
Overview UI

### ISSUE THREAD

**Issue by ECALINK** [Electra-project/electra-desktop#98]
Overview should contain the account information rather than the recent transactions. QR code on overview for easy access, as well as QR code on each account detailed view (could be a small icon that enlarges when clicked).

For example: 
![overview-with-accounts-01](https://user-images.githubusercontent.com/38509850/38957088-ef7c6dca-439c-11e8-861c-3181f582a070.png)

**Comment by ivangabriele** [comment]
Yes I also think this is a good idea. Do you confirm that @ruannelloyd ?

**Comment by ivangabriele** [comment]
I close this one as the planned redesign for the v1.2.0 will include a final decision about that.
